# Generated by Django 2.2.1 on 2019-05-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('address_final', models.CharField(max_length=255)),
                ('time_on', models.DateTimeField()),
                ('time_up', models.DateTimeField()),
                ('is_finish', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PreferredLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('score', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
                ('gender', models.IntegerField(max_length=8)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('choose', models.CharField(max_length=3)),
                ('num', models.IntegerField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengtou.PreferredLocation')),
            ],
        ),
        migrations.CreateModel(
            name='CommonProblem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengtou.User')),
            ],
        ),
        migrations.CreateModel(
            name='AdvWare',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengtou.Adv')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_start', models.CharField(max_length=255)),
                ('estimated_time', models.TimeField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengtou.Activity')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengtou.User')),
                ('voting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengtou.Voting')),
            ],
            options={
                'unique_together': {('user_id', 'activity_id')},
            },
        ),
    ]
