# Generated by Django 2.2.1 on 2019-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengtou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_finish',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='preferredlocation',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voting',
            name='num',
            field=models.IntegerField(),
        ),
    ]
