# Generated by Django 2.2.1 on 2019-05-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengtou', '0002_auto_20190508_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='voting_id',
            new_name='voting',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='address_id',
            new_name='address',
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('user', 'activity')},
        ),
    ]
