# Generated by Django 2.2.1 on 2019-05-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengtou', '0004_auto_20190512_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='address_start',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='estimated_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='voting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengtou.Voting'),
        ),
    ]
