# Generated by Django 2.2.1 on 2019-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengtou', '0005_auto_20190512_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address_final',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_finish',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_up',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commonproblem',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commonproblem',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commonproblem',
            name='problem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commonproblem',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='preferredlocation',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preferredlocation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preferredlocation',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preferredlocation',
            name='type',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='choose',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
